### ISSUE TITLE
Check for installed languages

### ISSUE THREAD

**Issue by jeroen** [ropensci/tesseract#1]
Try to find a way to test for installed languages without initializing tesseract. On Debian a common problem is that people forget to install `tesseract-ocr-eng`.

**Comment by amitdo** [comment]
>On Debian a common problem is that people forget to install tesseract-ocr-eng.

https://packages.debian.org/stretch/tesseract-ocr

    dep: libtesseract3 (>= 3.03~)
        Tesseract OCR library 

    dep: tesseract-ocr-eng (>= 3.01~)
        tesseract-ocr language files for English 

    dep: tesseract-ocr-equ
        tesseract-ocr language files for equations 

    dep: tesseract-ocr-osd
        tesseract-ocr language files for script and orientation

**Comment by jeroenooms** [comment]
The R package does not depend on `tesseract-ocr`, only on `libtesseract-dev`.

**Comment by amitdo** [comment]
Anyway, you can easily reimplement what Tesseract do in `TessBaseAPI::GetAvailableLanguagesAsVector()` in your favourite PL.

https://github.com/tesseract-ocr/tesseract/blob/ed4c4c6bf/api/baseapi.cpp#L367

You might need this method:
```
    const char * TessBaseAPI::GetDatapath() {
    return tesseract_->datadir.c_str();
    }
```

**Comment by jeroenooms** [comment]
The problem is that `GetDatapath` requires an initialized engine?

**Comment by amitdo** [comment]
You can also try:
`void TessBaseAPI::InitForAnalysePage()`

and test if you can then call `TessBaseAPI::GetAvailableLanguagesAsVector()`

**Comment by jeroenooms** [comment]
If I call `InitForAnalysePage`, it no longer segfaults but `GetDatapath()`returns an empty string:

```cc
tesseract::TessBaseAPI api;
api.InitForAnalysePage();
printf("data path: %s", api.GetDatapath());
```

**Comment by amitdo** [comment]
You can search for some common paths...

**Comment by jeroenooms** [comment]
OK that gets messy, I don't want to reverse engineer tesseract logic to find languages. I guess there is no good method for doing this :(

**Comment by amitdo** [comment]
You need to searcg for `*.traineddata` files in the user system. That's what Tesseract does.
