### ISSUE TITLE
non character options

### ISSUE THREAD

**Issue by jwijffels** [ropensci/tesseract#11]
FYI. It looks like the package can only handle character options. 
As in something like this will not work.

engine <- tesseract(language = "eng", options = list(load_system_dawg = 0L, load_freq_dawg = 0L))

and does this set the option correctly?
engine <- tesseract(language = "eng", options = list(load_system_dawg = "0", load_freq_dawg = "0"))

**Comment by jeroen** [comment]
Hi @nasradev I have overhauled the way parameters are used. Can you try the dev version of tesseract and see if this works better now?

```r
devtools::install_github("ropensci/tesseract")
```

**Comment by jeroen** [comment]
This should be fixed in tesseract 2.0 on CRAN. Please open an new issue if you still find problems.
