### ISSUE TITLE
changing value of "minimum characters to try"

### ISSUE THREAD

**Issue by ShahrukhSatti21** [ropensci/tesseract#13]
I'm working on text extraction from vehicle number plate images and want to avoid getting "Too few characters, skipping this page" error. I'm working in Rstudio. Tesseract-ocr has option to change variable **minCharactersToTry** but how do I implement that using Rstudio? Could you please spare a little time to guide me through that?
 
Any assistance is appreciated.

**Comment by jeroen** [comment]
I can't find any notion of `minCharactersToTry` on google or in the tesseract source.

**Comment by ShahrukhSatti21** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/ccmain/osdetect.cpp

Find kMinCharactersToTry in this code.

**Comment by jeroen** [comment]
OK but this is hardcoded c++ not a parameter a user can set?

**Comment by ShahrukhSatti21** [comment]
Okay, so what do I need to do to avoid getting this "Too few characters" error? 
I'm sorry, I'm only a beginner :|
Here this might help

![eromgfr](https://cloud.githubusercontent.com/assets/26629513/24264903/988313c8-1023-11e7-864e-6bcd580b1f65.png)

**Comment by jeroen** [comment]
Dupe https://github.com/ropensci/tesseract/issues/15. This message can be ignored.
