### ISSUE TITLE
Bug with Japanese

### ISSUE THREAD

**Issue by histmr** [ropensci/tesseract#14]
I cannot get tesseract to work with Japanese. These lines work as expected

    tesseract_download("fra")
    french <- tesseract("fra")
    text <- ocr("http://ocrapiservice.com/static/images/examples/french_text.png", engine = french)

However, simply putting in "jpn" . . .

    tesseract_download("jpn")
     Downloaded: 42.32 MB  (100%)
    [1] "/Users/histmr/Library/R/3.3/library/tesseract/tessdata/jpn.traineddata"
    japanese <- tesseract("jpn")
    Failed loading language 'jpn'
    Tesseract couldn't load any languages!
    Error in tesseract_engine_internal(datapath, language) : 
    Unable to find training data for: jpn

Yet tesseract can partly see the files!

    tesseract_info()
    $datapath
    [1] "/Users/histmr/Library/R/3.3/library/tesseract/tessdata/"

    $available
    [1] "eng" "fra" "jpn"

    $version
    [1] "3.05.00"

**Comment by jeroen** [comment]
I can reproduce this. Very strange.

**Comment by jeroen** [comment]
Maybe related to https://github.com/tesseract-ocr/tesseract/issues/1250

**Comment by jeroen** [comment]
Seems like we need to load with `Sys.setlocale(locale="C")` indeed. Very strange.
