### ISSUE TITLE
Avoid leptonica

### ISSUE THREAD

**Issue by jeroen** [ropensci/tesseract#16]
The `api->SetImage()` function also has a method for bitmaps. Perhaps we can use this to pass bitmaps generated from `magick()` so we can avoid leptonica alltogether.

**Comment by amitdo** [comment]
Tesseract itself depend on leptonica and can't work without it.

>The api->SetImage() function also has a method for bitmaps.

Tesseract converts this to leptonica's Pix.

**Comment by jeroen** [comment]
OK good to know. Very unfortunate though.
