### ISSUE TITLE
Warning. Invalid resolution 0 dpi. Using 70 instead.

### ISSUE THREAD

**Issue by Onno91** [ropensci/tesseract#17]
When reading my tiff files which are set at 600 DPI, tesseract can not find the DPI setting and reverts to the default of 70 DPI. 

Can we change the default resolution and/or set resolution manually? 

I see you referenced this problem earlier in a different thread @jeroen 
![knipsel](https://user-images.githubusercontent.com/31956262/30427188-2ba2a826-994f-11e7-8c2a-985db6498d93.JPG)

**Comment by jeroen** [comment]
This is an issue in the libresseract code. If you Google the error you find many other complaints from non R users. I don't think there is a solution.

**Comment by syzer** [comment]
@jeroen 
you are correct.
it's also with shell usage
