### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by under-score** [ropensci/tesseract#18]
It seems that options are not recognized, when trying
`options = list(classify_bln_numeric_mode = "0")`

**Comment by eipi10** [comment]
I'm having this issue as well. For example, when I try `x = ocr(img, options=list(textord_tabfind_find_tables="1"))` (in order to try and OCR a table from and image), I get the following error:

```
Error in ocr(img, options = list(textord_tabfind_find_tables = "1")) : 
  unused argument (options = list(textord_tabfind_find_tables = "1"))
```

Would it be possible to add an example or two to the help for `?ocr` to show how to use the `options` argument? There's a link to the `tesseract` engine options page, but no information about how to correctly specify these options in the `ocr` function.

**Comment by jeroen** [comment]
I have overhauled the way parameters are used. Can you try the dev version of tesseract and see if this works better now?

```r
devtools::install_github("ropensci/tesseract")
```

**Comment by jeroen** [comment]
This should be fixed in tesseract 2.0 on CRAN. Please open an new issue if you still find problems.

**Comment by qarmitage** [comment]
I'm having what I believe is the same issue with the newest release. 

`engine<-tesseract(options=list(tessedit_char_whitelist="0123456789"))
vs. 
engine<-tesseract(options=list(tessedit_char_whitelist="ABCDEFGHIJKLMNOPQRSTUVWXYZ"))


cell_text <- ocr(file, engine=engine, HOCR=FALSE)`

Appear to be generating the same results. 
Perhaps I'm confused.

**Comment by jeroen** [comment]
You're not confused, unfortunately this option is no longer supported in Tesseract 4: See https://github.com/tesseract-ocr/tesseract/issues/751 or https://github.com/tesseract-ocr/tesseract/issues/2066

**Comment by sowla** [comment]
Thank you for a really awesome package! Bartłomiej Uliasz says [here](https://stackoverflow.com/questions/2363490/limit-characters-tesseract-is-looking-for):

> To use whitelist in a config file or using the -c tessedit_char_whitelist=... command-line switch, in the newest 4.0 version you will have to set OCR Engine mode to the "Original Tesseract only".

I don't know if it applies to the R version or how difficult to it is to implement, but I stumbled across the post and thought I'd share it here in case someone who can judge whether this information is useful might see it :)

**Comment by jeroen** [comment]
The whitelist option is now supported again in Tesseract 4.1 (on CRAN now).
