### ISSUE TITLE
Output hocr and pdf

### ISSUE THREAD

**Issue by robszabo** [ropensci/tesseract#20]
First of all, thanks for this great functionality by simplifying the usage of tesseract from R and the possibility to download the language files with a single line of r-code. This is powerful!

It would also be really nice in case it would be possible to output an ocr'ed document in hocr format or as a searchable pdf directly. This would make the package even more simple to use for people (like me) that doesn't have the skills to configure or override the settings in tesseract.
With an additional parameter "output" to the ocr function that could be one of {"text", "hocr" or "pdf"} it could look like this:
out <- ocr("test.tif", engine = tesseract("swe"), output = "hocr")

I think this would make this R package very strong in terms of how widely it could be used.

Again, thanks for a great work!

**Comment by jeroen** [comment]
Thank you for the suggestion. I have added a parameter to get the HOCR output. Can you test this?

**Comment by robszabo** [comment]
Works like a charm! Thanks a lot! :-)

**Comment by jeroen** [comment]
on cran now
