### ISSUE TITLE
Processing bitmap with Tesseract

### ISSUE THREAD

**Issue by boohbah94** [ropensci/tesseract#21]
I'm working on a project with bitmap images - specifically raw bitmap arrays of PDF pages extracted through the pdf_render_page command in the pdftools package. I'd like to be able to pass them directly to Tesseract via this package for OCR - is this something that's possible? Are there decent workarounds if it's not possible?

If my question's unclear, let me know and I'll provide additional info.

**Comment by jeroen** [comment]
Dupe https://github.com/ropensci/tesseract/issues/16
