### ISSUE TITLE
USE_STD_NAMESPACE      master       v2.0 v1.8 

### ISSUE THREAD

**Issue by amitdo** [ropensci/tesseract#24]
Tesseract is now at beta 1 stage. 

This version uses std:string everywhere.   `USE_STD_NAMESPACE` is not needed anymore.
@jeroen,  you can revert a94e339e4.

Off-topic: https://gist.github.com/amitdo/7c7a522004dd79b398340c9595b377e1#gistcomment-2380042.

**Comment by jeroen** [comment]
Unfortunately Debian/Ubuntu have  shipped [an alpha release of tesseract](https://packages.ubuntu.com/bionic/tesseract-ocr), so we need to include this workaround to make the R bindings work on e.g. Ubuntu bionic.

**Comment by amitdo** [comment]
What DebIan/Ubuntu calls 'alpha' was tagged as '4.0.0-**beta**.1' in Tesseract (don't ask...).

DebIan & Ubuntu have their own patch:
https://sources.debian.org/patches/tesseract/4.00%7Egit2219-40f43111-1.2/fix-up-headers/

Tesseract fixed the issue after that beta.1 tagged version.

**Comment by jeroen** [comment]
OK you are right it seems Debian/Ubuntu had patched the issue downstream. Removing the workaround: https://github.com/ropensci/tesseract/commit/d89793d633f6c8b14f5ba62e7bc2b8cb1b7b5b4c

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/ad6f3b412a9a
is same as the Ubuntu patch.

but Ubuntu does not have this one:
https://github.com/tesseract-ocr/tesseract/commit/c6e8916065bc

Is this a problem for you?
