### ISSUE TITLE
magick dependency

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/tesseract#29]
This is probably not an issue, but rather a suggestion and an invitation to discussion.

ImageMagick installation on Windows may be ... a little involved. Is there a reason you want to keep dependency on `magick` in `tesseract`? You only seem to use `magick` for saving `magick` images, so if you save them using other tools, you are afraid of losing class (do you even need to save them, as argued in #28)?  I imagine that removing dependency on magick will help wider adoption of `tesseract`, particularly by folks to tend to use `imager` and other R image processing platforms

**Comment by jeroen** [comment]
The magick package on windows is self contained and does not depend on imagemagick.

**Comment by dmi3kno** [comment]
I apologize for asking. You are right that magick is self-contained. I would love to hear your view on #28 re: TMP images. Thank you again and sorry for my lack of diligence.
