### ISSUE TITLE
Unable to install R package with tesseract 4.0.0 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by arcruz0** [ropensci/tesseract#30]
Hi! I could use this package without any problems while having tesseract 3 installed. However, after getting tesseract 4 (from the PPA) I cannot longer install the R package.

This is what I get in the command line with `tesseract -v`:
```
tesseract 4.0.0-beta.3-195-ge9cd
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
```
And here's the error after `devtools::install_github("ropensci/tesseract")` (being basically the same after `install.packages("tesseract")`):

```
Downloading GitHub repo ropensci/tesseract@master
from URL https://api.github.com/repos/ropensci/tesseract/zipball/master
Installing tesseract
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpZhNFsR/devtools180279de2ce5/ropensci-tesseract-6514c58'  \
  --library='/home/andres/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘tesseract’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/leptonica
Using PKG_LIBS=-ltesseract
Using CXX11CPP: g++ -E -std=gnu++11
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because tesseract was not found. Try installing:
 * deb: libtesseract-dev libleptonica-dev (Debian, Ubuntu, etc)
 * rpm: tesseract-devel leptonica-devel (Fedora, CentOS, RHEL)
 * csw: libtesseract_dev (Solaris)
 * brew: tesseract (Mac OSX)
If tesseract is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a tesseract.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘tesseract’
* removing ‘/home/andres/R/x86_64-pc-linux-gnu-library/3.4/tesseract’
Installation failed: Command failed (1)
```
However, those libraries are installed. Here's the output of `apt list --installed | egrep "(libtess)|(libleptonica)"`:
```
libleptonica-dev/xenial,now 1.76.0-1+nmu1ppa1~xenial1 amd64 [installed]
libtesseract-dev/xenial,now 4.00~git2790-e9cd6024-1ppa1~xenial1 amd64 [installed]
libtesseract4/xenial,now 4.00~git2790-e9cd6024-1ppa1~xenial1 amd64 [installed,automatic]
```

I'm not really familiar with pkg-config, but in case it's useful, this is the output of `pkg-config --list-all | grep ^tess` in the command line:
```
tesseract                      tesseract - An OCR Engine that was developed at HP Labs between 1985 and 1995... and now at Google.
``` 

Thanks in advance!

**Comment by jeroen** [comment]
Which PPA do you use?

**Comment by jeroen** [comment]
I noticed they pushed another release to the PPA. Can you try updating? Maybe the one you had was temporarily broken.

**Comment by jeroen** [comment]
Hmm it looks like they moved the headers into a subdirectory `/include/tesseract/` but didn't update the pkg-config file accordingly.

**Comment by stweil** [comment]
Latest Tesseract requires an update of your sources: instead of `#include <baseapi.h>`, Tesseract now requires `#include <tesseract/baseapi.h>` (and similar for all other API header files of Tesseract).

**Comment by jeroen** [comment]
But if we change to `#include <tesseract/baseapi.h>` then users can't compile anymore on systems with previous versions of tesseract...

**Comment by jeroen** [comment]
@arcruz0 can you confirm that this problem is solved? Try installing the dev version:

```r
remotes::install_github("ropensci/tesseract")
```

**Comment by arcruz0** [comment]
It works now, thanks a lot!

**Comment by jeroen** [comment]
Ok this is on cran now

**Comment by RobsonScosta** [comment]
Hi! I'm trying to install in RStudio I'm not getting it.

remotes::install_github("ropensci/tesseract")

I do the installation process, and it displays the following result.

Downloading GitHub repo ropensci/tesseract@HEAD
✔  checking for file ‘/tmp/RtmpLuDJUL/remotes9d2d311efa0d/ropensci-tesseract-ead4c51/DESCRIPTION’ (497ms)
─  preparing ‘tesseract’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘tesseract_5.1.0.tar.gz’
   
Installing package into ‘/datahome/robson/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘tesseract’ ...
** using staged installation
Package tesseract was not found in the pkg-config search path.
Perhaps you should add the directory containing `tesseract.pc'
to the PKG_CONFIG_PATH environment variable
Package 'tesseract', required by 'world', not found
Using PKG_CFLAGS=-I/usr/include/tesseract -I/usr/include/leptonica
Using PKG_LIBS=-ltesseract
Using CXX11CPP: g++ -E -std=gnu++11
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find 'tesseract' system library. Try installing:
 * deb: libtesseract-dev libleptonica-dev (Debian, Ubuntu, etc)
 * rpm: tesseract-devel leptonica-devel (Fedora, CentOS, RHEL)
 * brew: tesseract (Mac OSX)
If tesseract is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a tesseract.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
tools/test.cpp:1:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘tesseract’
* removing ‘/datahome/robson/R/x86_64-pc-linux-gnu-library/4.1/tesseract’
installation of package ‘/tmp/RtmpLuDJUL/file9d2d338011d2/tesseract_5.1.0.tar.gz’ had non-zero exit status

How should I proceed to install the library, if I need to convert the article "PDF", which contains colors and images into text; to perform sentiment analysis.

**Comment by jeroen** [comment]
Try
```r
system("sudo apt-get install -y libtesseract-dev libleptonica-dev")
```
