### ISSUE TITLE
Turning on legacy OCR engine mode

### ISSUE THREAD

**Issue by dmypstl** [ropensci/tesseract#39]
Whitelist and blacklist are not implemented in version 4.0 ([issue](https://github.com/tesseract-ocr/tesseract/issues/751)) and user patterns do not work ([issue](https://github.com/tesseract-ocr/tesseract/issues/403)). In this issue people recommend turning on legacy OEM using `--oem 0` option flag. This option is not part of configs, but rather belong to the [engine itself](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage), like language. 

Could we please enable more ocr options as arguments in `tesseract::tesseract()`, including `oem` to be able to temporarily switch to older version of the engine.

**Comment by jeroen** [comment]
The main problem is that v3 uses a different format for training data than v4. So we would need to manage different sets of training data within a single r package.

**Comment by dmypstl** [comment]
I see. This is pretty unfortunate. Maybe you could tag latest stable version before engine update and invite people to optionally install it with `remotes::install_github("ropensci/tesseract@v3.0.4")` or whatever the last version was before it was updated to 4.0. I think found the relevant commit now, but it is pretty awkward to refer to it.

**Comment by jeroen** [comment]
The easiest way to install an old version of the R package is using MRAN snapshots:

```r
install.packages('tesseract', repos = 'https://cran.microsoft.com/snapshot/2018-09-01/')
```

**Comment by jeroen** [comment]
The whitelist / blacklist options are now supported in tesseract 4.1 (on cran).
