### ISSUE TITLE
Use on Windows 7 with German training data ("umlauts")? 

### ISSUE THREAD

**Issue by luke-a** [ropensci/tesseract#4]
How do I use the package with German training data? For example, this won't work as expected: 
```
library(tesseract)
library(magick)
library(magrittr)
packageVersion("tesseract")
# [1] ‘1.2’

# download german training data
dir.create(dir <- file.path(tempdir(), "tessdata"))
fn <- "https://github.com/tesseract-ocr/tessdata/raw/master/deu.traineddata"
download.file(fn, file.path(dir, basename(fn)), mode="wb")

# download and crop example jpg image with umlauts
download.file("https://i.ytimg.com/vi/mr-mCMtISfA/maxresdefault.jpg", tf <- tempfile(fileext = ".jpg"), mode="wb")
tf %>% image_read %>% image_crop("900x600+500+300") %>% image_write(tf2 <<- tempfile(fileext = ".jpg"))

# initialize and predict: 
tesseract("deu", tempdir())
# <tesseract engine>
#  loaded: deu 
#  datapath: C:\Windows\TEMP\Rtmpa4DpNt/tessdata/ 
#  available: deu 

cat(ocr(tf2))
# 56H

## which is wrong. Correct would be äöü
```

I dunno if this is the right place to ask, but... I'll give it a try. And thanks for the package(s) btw.

**Comment by jeroenooms** [comment]
You need to use:

```r
engine <- tesseract("deu", tempdir())
ocr("tf2", engine = engine)
```

Also note that your example image is a bit unfortunate because it contains no actual german words. Can you try to start with a paragraph of german text?

**Comment by jeroenooms** [comment]
<img width="236" alt="testger" src="https://cloud.githubusercontent.com/assets/216319/20387262/8c0e7b04-acbf-11e6-9c85-351049c59223.png">

If I try the test image above I get:

```r
> url = 'https://cloud.githubusercontent.com/assets/216319/20387262/8c0e7b04-acbf-11e6-9c85-351049c59223.png'
> ocr(url)
[1] "Das Glﬂck hilft dem Kl'flhnen.\n\n"


> ocr(url, tesseract('deu'))
[1] "Das Glück hilft dem Kühnen.\n\n"
```

**Comment by luke-a** [comment]
Thanks for your reply. I did not get that `tesseract` returns an object that I can pass on to `ocr`. That did the trick and the example works fine, now. Great stuff. 

(Side note: I also thought the training data are characters, not words, therefore the example.)
