### ISSUE TITLE
Multi langague text

### ISSUE THREAD

**Issue by Tomer-Tsaban** [ropensci/tesseract#42]
Hi, 
I have text files with 2 languages (hebrew and english).
when using ocr function with each engine (heb or eng), the corresponding parts of the text are identified correctly. the rest however is wrong.
I know that there is a way to use 2 languages in tesseract, but is there a way to do so using the R package?

Thanks a lot for your help!!
Tomer

**Comment by jeroen** [comment]
This seems to work for me (tesseract 4.1):

```r
tesseract('eng+nld')
## <tesseract engine>
## loaded: eng nld 
## datapath: /Users/jeroen/Library/Application Support/tesseract4/tessdata/ 
## available: eng fra nld osd spa
```

**Comment by Tomer-Tsaban** [comment]
seems to work! thanks very much
