### ISSUE TITLE
Unable to install tesseract (R package) on docker 

### ISSUE THREAD

**Issue by babi0929** [ropensci/tesseract#46]
Trying to install the R package(tesseract) on docker. I get the following error message. Please help!

/usr/bin/ld: cannot find -larchive
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:6: tesseract.so] Error 1
ERROR: compilation failed for package ‘tesseract’
* removing ‘/usr/local/lib/R/site-library/tesseract’

The downloaded source packages are in
        ‘/tmp/RtmpXMY0C6/downloaded_packages’
Warning message:
In install.packages("tesseract") :
  installation of package ‘tesseract’ had non-zero exit status

------------------------------
FROM rocker/r-base

RUN apt-get update -qq && apt-get install -y \
	tesseract-ocr\
	libtesseract-dev\
	libleptonica-dev\
	tesseract-ocr-eng\
	libpoppler-cpp-dev\
	libmagick++-dev\
    libxml2 \
    libcurl4-openssl-dev \
    libxml2-dev \
    git-core \
    libssl-dev \
    libgtk2.0-dev \ 
    libcairo2-dev \ 
    libxt-dev \
    xvfb \ 
    xauth \
    libfftw3-dev \
    libx11-dev \
    libtiff-dev \
    xfonts-base

#RUN R -e "install.packages('tesseract')"
RUN R -e "install.packages('plumber')"
RUN R -e "install.packages('stringr')"
RUN R -e "install.packages('lubridate')"
RUN R -e "install.packages('stringdist')"
RUN R -e "install.packages('mime')"
RUN R -e "install.packages('Rook')"
RUN R -e "install.packages('magick')"
RUN R -e "install.packages('tm')"
RUN R -e "install.packages('pdftools')"
RUN R -e "install.packages('devtools')"
RUN R -e "install.packages('tesseract')"
#RUN R -e "devtools::install_github('ropensci/tesseract')"

**Comment by jeroen** [comment]
This is a temporary bug in debian which has already been fixed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949140

Either update the docker image, or as a workaround you can use `apt-get install libarchive-dev`
