### ISSUE TITLE
Tesseract package installation issue from R studio in CentOS 7 server

### ISSUE THREAD

**Issue by ghareesh** [ropensci/tesseract#49]
Hi Team..
I am running R studio on CentOs 7 server.. 
Below is tesseract details installed at OS level
 tesseract --version
tesseract 4.1.0
 leptonica-1.75.3
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7

I am trying to install tesseract package from R studio.. 

It shows below error.. 

* installing *source* package ‘tesseract’ ...
** package ‘tesseract’ successfully unpacked and MD5 sums checked
Package tesseract was not found in the pkg-config search path.
Perhaps you should add the directory containing `tesseract.pc'
to the PKG_CONFIG_PATH environment variable

I am not able to understand the next steps on troubleshooting this error.. Could you please help.. 

R Version details.: 
 version
               _                           
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing

**Comment by jeroen** [comment]
Did you do:

```
sudo yum install epel-release
sudo yum install tesseract-devel leptonica-devel
```

**Comment by ghareesh** [comment]
Yes jeron.. this is info
[root@hdop-stg-r1 skatpally]# rpm -qa |grep tesseract-devel
tesseract-devel-3.04.00-3.el7.x86_64
[root@hdop-stg-r1 skatpally]# rpm -qa |grep leptonica-devel
leptonica-devel-1.72-2.el7.x86_64
[root@hdop-stg-r1 skatpally]# rpm -qa |grep epel-release
epel-release-7-11.noarch

**Comment by jeroen** [comment]
So you say above that you run `tesseract 4.1.0` but then it looks like you run `tesseract-devel-3.04.00`? Did you install multiple versions?

Can you show the full output of `install.packages("tesseract")` ?

**Comment by ghareesh** [comment]
Hi Jeroen.. 
Yes.. you sare right there was 3. version as well preinstalled.. Admin has removed it and reinstalled.. Now it is working fine.. Thanks for helping here ..
