### ISSUE TITLE
train own tesseract model

### ISSUE THREAD

**Issue by jwijffels** [ropensci/tesseract#50]
I have some training data on scans of 16th century dutch texts containing a mixture of dutch/french/latin. 
Of people who payed something for renting some land or a house. 
I want to train a new model instead of using the existing pretrained models as I need to compare such a model to other OCR models which I have locally trained.

I can put the training data in the format defined at https://github.com/tesseract-ocr/tesstrain, namely in this format https://github.com/tesseract-ocr/tesstrain/blob/master/ocrd-testset.zip in order to train a model myself.
Does anyone know if it will be uberhaupt possible once trained to used this model using this R package? Will there be version conflicts. Anyone tried already?
I'm running Ubuntu with tesseract `4.1.1`

**Comment by jeroen** [comment]
I think it should be possible to use custom trained data, in the same way as any of the standard languages. Any data that you train with 4.x should be compatible with tesseract 4.x engines.

**Comment by jwijffels** [comment]
thanks, indeed seems to work.

**Comment by jeroen** [comment]
Would you mind writing a short paragraph in the readme, or a vignette (whatever you like) about the steps to do this?

**Comment by jwijffels** [comment]
For testing I basically followed the tutorial at https://github.com/tesseract-ocr/tesstrain
Unzipped the training data and ran

``` 
make training MODEL_NAME=foof
```
providing a model with character error rate of 1.242%. Next loading the model worked in tesseract:

![Knipsel](https://user-images.githubusercontent.com/1710810/94658184-c384a480-0302-11eb-8e4e-b1d5dceaa87f.PNG)

```
> library(magick)
Linking to ImageMagick 6.9.10.23
Enabled features: fontconfig, freetype, fftw, lcms, pango, webp, x11
Disabled features: cairo, ghostscript, rsvg
Using 4 threads
> library(tesseract)
> model <- tesseract("foo", datapath = "/home/jwijffels/tesstrain/data")
Failed to load any lstm-specific dictionaries for lang foo!!
> img   <- image_read("/home/jwijffels/tesstrain/data/foo-ground-truth/alexis_ruhe01_1852_0018_022.tif")
> img
# A tibble: 1 x 7
  format width height colorspace matte filesize density
  <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
1 TIFF     976     47 Gray       FALSE    18784 72x72  
> text  <- ocr(img, engine = model, HOCR = FALSE)
> cat(text)
ich denke. Aber was die ſelige Frau Geheimräthin
> readLines("/home/jwijffels/tesstrain/data/foo-ground-truth/alexis_ruhe01_1852_0018_022.gt.txt")
[1] "ich denke. Aber was die ſelige Frau Geheimräthin"
```
