### ISSUE TITLE
loading tesseract causes RStudio to crash

### ISSUE THREAD

**Issue by dwyker** [ropensci/tesseract#60]
Running library(tesseract) causes R to crash

R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by samuel-chen-mil-navy** [comment]
Yes!! tesseract causes R 4.2.0 to crash.  Works okay with 4.1.x.  Tested on multiple machines.
Does package need new binaries on CRAN for new 4.2.0?

**Comment by thomasairbag** [comment]
I am experiencing this problem also.
R version: 4.2.0 (2022-04-22 ucrt)
Running: Windows 11 Home 21H2

**Comment by jeroen** [comment]
Hmm I cannot reproduce this. Seems to load fine on my Windows...

**Comment by thomasairbag** [comment]
Is there any further information I can give to help?

**Comment by samuel-chen-mil-navy** [comment]
Update:  On both work and home machine, library(tesseract) take about 5 - 6 minutes  to load.  So R didn't crash.  Just it takes an unreasonably long time to load.  Can this be fixed?  Home machine:

R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

**Comment by jeroen** [comment]
I tried building a new version of tesseract. Can you please test if the problem still appears with tesseract 5.1.0? To install, run in a __clean empty r session__

```r
install.packages("tesseract", repos = 'https://ropensci.r-universe.dev')
```

**Comment by samuel-chen-mil-navy** [comment]
The package is still taking a long time to load, but maybe a little bit faster!  On home machine, I deleted the tesseract directory from my windows library folder and installed from ropensci repo.  I will test on work machine and report.

**Comment by samuel-chen-mil-navy** [comment]
The newly compiled package might even be *slower*.  This morning, I timed with stopwatch (smartphone) and got approximately five and half minutes.  Now...

> beginTime = Sys.time()
> library(tesseract)
> endTime = Sys.time()
> endTime - beginTime
Time difference of 6.699568 mins
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

**Comment by rafaelkiko** [comment]
still getting a fatal error and aborted session with the new package,
same R version, Platform and Windows as before

**Comment by jeroen** [comment]
This has been fixed now in the upstream libtesseract code: https://github.com/tesseract-ocr/tesseract/issues/3830

**Comment by jeroen** [comment]
I have deployed a fixed version to r-universe, and will submit to CRAN soon:

```r
install.packages("tesseract", repos = 'https://ropensci.r-universe.dev')
```
