### ISSUE TITLE
Getting character confidence

### ISSUE THREAD

**Issue by SampurnR** [ropensci/tesseract#8]
Hey.

First of all, please allow me to thank and congratulate you guys on the excellent work you have done in this repository. 

Now, on to the issue.
Is there any way of getting the confidence level of every character in the ocr result?
[As displayed in the Tesseract training wiki.](https://github.com/tesseract-ocr/tesseract/wiki/APIExample#example-of-iterator-over-the-classifier-choices-for-a-single-symbol)

Currently, I'm doing the following 
`library(tesseract) 

tes <- tesseract(language = "neelam", options = list(tessedit_dump_choices = "1", textord_heavy_nr = "1"))
 
text <- ocr("/home/sampurn/projects/ICR-R/training/cursive.neelam.exp5.png", engine = tes)`

..which yields the following:
`Info in pixReadStreamPng: converting (cmap + alpha) ==> RGBA
Info in pixReadStreamPng: converting 8 bpp cmap with alpha ==> RGBA
Pass1: px [p [70 ] x [78 ] ]
Pass1: B [B [42 ] ]
Pass1: c [c [63 ] ]
Pass1: D [D [44 ] ]
Pass1: t [t [74 ] ]
Pass1: N [N [4e ] ]
Pass1: G [G [47 ] ]
Pass1: H [H [48 ] ]
Pass1: I [I [49 ] ]
Pass1: J [J [4a ] ]
Pass1: K [K [4b ] ]
Pass1: l [l [6c ] ]
Pass1: M [M [4d ] ]
Pass1: NopQRQTUvave [N [4e ] o [6f ] p [70 ] Q [51 ] R [52 ] Q [51 ] T [54 ] U [55 ] va [76 61 ] v [76 ] e [65 ] ]
Pass1: k [k [6b ] ]
Pass1: l [l [6c ] ]
Pass1: M [M [4d ] ]
Pass1: a [a [61 ] ]
Pass1: b [b [62 ] ]
Pass1: e [e [65 ] ]
Pass1: d [d [64 ] ]
Pass1: E [E [45 ] ]
Pass1: f [f [66 ] ]
Pass1: g [g [67 ] ]
Pass1: h [h [68 ] ]
Pass1: lj [l [6c ] j [6a ] ]
Pass1: n [n [6e ] ]
Pass1: o [o [6f ] ]
Pass1: p [p [70 ] ]
Pass1: q [q [71 ] ]
Pass1: ri [r [72 ] i [69 ] ]
Pass1: g [g [67 ] ]
Pass1: t [t [74 ] ]
Pass1: u [u [75 ] ]
Pass1: v [v [76 ] ]
Pass1: w [w [77 ] ]
Pass1: x [x [78 ] ]
Pass1: p [p [70 ] ]
Pass1: e [e [65 ] ]
Pass1: N [N [4e ] ]
Pass1: .ie. [. [2e ] i [69 ] e [65 ] . [2e ] ]
Pass1: B [B [42 ] ]
Pass1: ep [e [65 ] p [70 ] ]
Pass1: J [J [4a ] ]
Pass1: c [c [63 ] ]
Pass1: T [T [54 ] ]
Pass1: B [B [42 ] ]
Pass1: oC [o [6f ] C [43 ] ]
Pass1: xo [x [78 ] o [6f ] ]
Pass1: Q [Q [51 ] ]
Pass1: a [a [61 ] ]
Pass1: C [C [43 ] ]
Pass1: D [D [44 ] ]
Pass1: E. [E [45 ] . [2e ] ]
Pass1: J [J [4a ] ]
Pass1: Ig [I [49 ] g [67 ] ]
Pass1: The [T [54 ] h [68 ] e [65 ] ]
Pass1: quilck [q [71 ] u [75 ] i [69 ] l [6c ] c [63 ] k [6b ] ]
Pass1: brown [b [62 ] r [72 ] o [6f ] w [77 ] n [6e ] ]
Pass1: dog [d [64 ] o [6f ] g [67 ] ]
Pass1: dumped [d [64 ] u [75 ] m [6d ] p [70 ] e [65 ] d [64 ] ]
Pass1: over [o [6f ] v [76 ] e [65 ] r [72 ] ]
Pass1: the [t [74 ] h [68 ] e [65 ] ]
Pass1: lazy [l [6c ] a [61 ] z [7a ] y [79 ] ]
Pass1: fox [f [66 ] o [6f ] x [78 ] ]
Pass1: m [m [6d ] ]
Pass1: . [. [2e ] ]
Pass1: d [d [64 ] ]
Pass1: the [t [74 ] h [68 ] e [65 ] ]
Pass1: quick [q [71 ] u [75 ] i [69 ] c [63 ] k [6b ] ]
Pass1: brown [b [62 ] r [72 ] o [6f ] w [77 ] n [6e ] ]
Pass1: dog [d [64 ] o [6f ] g [67 ] ]
Pass1: jumpe [j [6a ] u [75 ] m [6d ] p [70 ] e [65 ] ]
Pass1: over [o [6f ] v [76 ] e [65 ] r [72 ] ]
Pass1: the [t [74 ] h [68 ] e [65 ] ]
Pass1: lazy [l [6c ] a [61 ] z [7a ] y [79 ] ]
Pass1: fox [f [66 ] o [6f ] x [78 ] ]
Pass1: ROWN [R [52 ] O [4f ] W [57 ] N [4e ] ]
Pass1: DOG [D [44 ] O [4f ] G [47 ] ]
Pass1: JUMPED [J [4a ] U [55 ] M [4d ] P [50 ] E [45 ] D [44 ] ]
Pass1: THE [T [54 ] H [48 ] E [45 ] ]
Pass1: QUIcK [Q [51 ] U [55 ] I [49 ] c [63 ] K [4b ] ]
Pass1: B [B [42 ] ]
Pass1: ox [o [6f ] x [78 ] ]
Pass1: E [E [45 ] ]
Pass1: wrcv [w [77 ] r [72 ] c [63 ] v [76 ] ]
Pass1: P [P [50 ] ]
Pass1: ovER [o [6f ] v [76 ] E [45 ] R [52 ] ]
Pass1: TH [T [54 ] H [48 ] ]
Pass2: px [p [70 ] x [78 ] ]
Pass2: B [B [42 ] ]
Pass2: c [c [63 ] ]
Pass2: D [D [44 ] ]
Pass2: t [t [74 ] ]
Pass2: N [N [4e ] ]
Pass2: G [G [47 ] ]
Pass2: H [H [48 ] ]
Pass2: I [I [49 ] ]
Pass2: J [J [4a ] ]
Pass2: K [K [4b ] ]
Pass2: l [l [6c ] ]
Pass2: M [M [4d ] ]
Pass2: NoopQRQTUvave [N [4e ] o [6f ] o [6f ] p [70 ] Q [51 ] R [52 ] Q [51 ] T [54 ] U [55 ] va [76 61 ] v [76 ] e [65 ] ]
Pass2: k [k [6b ] ]
Pass2: l [l [6c ] ]
Pass2: M [M [4d ] ]
Pass2: a [a [61 ] ]
Pass2: b [b [62 ] ]
Pass2: e [e [65 ] ]
Pass2: d [d [64 ] ]
Pass2: E [E [45 ] ]
Pass2: f [f [66 ] ]
Pass2: g [g [67 ] ]
Pass2: h [h [68 ] ]
Pass2: lj [l [6c ] j [6a ] ]
Pass2: n [n [6e ] ]
Pass2: o [o [6f ] ]
Pass2: p [p [70 ] ]
Pass2: q [q [71 ] ]
Pass2: ri [r [72 ] i [69 ] ]
Pass2: g [g [67 ] ]
Pass2: t [t [74 ] ]
Pass2: u [u [75 ] ]
Pass2: v [v [76 ] ]
Pass2: w [w [77 ] ]
Pass2: x [x [78 ] ]
Pass2: p [p [70 ] ]
Pass2: e [e [65 ] ]
Pass2: N [N [4e ] ]
Pass2: .ie. [. [2e ] i [69 ] e [65 ] . [2e ] ]
Pass2: B [B [42 ] ]
Pass2: ep [e [65 ] p [70 ] ]
Pass2: J [J [4a ] ]
Pass2: c [c [63 ] ]
Pass2: T [T [54 ] ]
Pass2: B [B [42 ] ]
Pass2: oC [o [6f ] C [43 ] ]
Pass2: xo [x [78 ] o [6f ] ]
Pass2: Q [Q [51 ] ]
Pass2: a [a [61 ] ]
Pass2: C [C [43 ] ]
Pass2: D [D [44 ] ]
Pass2: E. [E [45 ] . [2e ] ]
Pass2: J [J [4a ] ]
Pass2: Ig [I [49 ] g [67 ] ]
Pass2: The [T [54 ] h [68 ] e [65 ] ]
Pass2: quilck [q [71 ] u [75 ] i [69 ] l [6c ] c [63 ] k [6b ] ]
Pass2: brown [b [62 ] r [72 ] o [6f ] w [77 ] n [6e ] ]
Pass2: dog [d [64 ] o [6f ] g [67 ] ]
Pass2: dumped [d [64 ] u [75 ] m [6d ] p [70 ] e [65 ] d [64 ] ]
Pass2: over [o [6f ] v [76 ] e [65 ] r [72 ] ]
Pass2: the [t [74 ] h [68 ] e [65 ] ]
Pass2: lazy [l [6c ] a [61 ] z [7a ] y [79 ] ]
Pass2: fox [f [66 ] o [6f ] x [78 ] ]
Pass2: m [m [6d ] ]
Pass2: . [. [2e ] ]
Pass2: d [d [64 ] ]
Pass2: the [t [74 ] h [68 ] e [65 ] ]
Pass2: quick [q [71 ] u [75 ] i [69 ] c [63 ] k [6b ] ]
Pass2: brown [b [62 ] r [72 ] o [6f ] w [77 ] n [6e ] ]
Pass2: dog [d [64 ] o [6f ] g [67 ] ]
Pass2: jumpe [j [6a ] u [75 ] m [6d ] p [70 ] e [65 ] ]
Pass2: over [o [6f ] v [76 ] e [65 ] r [72 ] ]
Pass2: the [t [74 ] h [68 ] e [65 ] ]
Pass2: lazy [l [6c ] a [61 ] z [7a ] y [79 ] ]
Pass2: fox [f [66 ] o [6f ] x [78 ] ]
Pass2: ROWN [R [52 ] O [4f ] W [57 ] N [4e ] ]
Pass2: DOG [D [44 ] O [4f ] G [47 ] ]
Pass2: JUMPED [J [4a ] U [55 ] M [4d ] P [50 ] E [45 ] D [44 ] ]
Pass2: THE [T [54 ] H [48 ] E [45 ] ]
Pass2: QUIcK [Q [51 ] U [55 ] I [49 ] c [63 ] K [4b ] ]
Pass2: B [B [42 ] ]
Pass2: ox [o [6f ] x [78 ] ]
Pass2: E [E [45 ] ]
Pass2: wrcv [w [77 ] r [72 ] c [63 ] v [76 ] ]
Pass2: P [P [50 ] ]
Pass2: ovER [o [6f ] v [76 ] E [45 ] R [52 ] ]
Pass2: TH [T [54 ] H [48 ] ]`

Please find my tesseract information [here](http://pastebin.com/cnTTWH8h).

PS. Let me know if I ought to ask this in a google forum/group.
Once again, thanks for your work.

**Comment by pldilley** [comment]
Hey guys, I am also very interested in this question.

**Comment by jeroen** [comment]
Try the new `ocr_data()` function or otherwise set `HOCR = TRUE` in `ocr()`.
