### ISSUE TITLE
HOCR support

### ISSUE THREAD

**Issue by Alanwe** [ropensci/tesseract#9]
Hi all,

Great work on getting this ported. 
Quick question does the tessedit_create_hoc option work. I've tried the following code and also tried a few alternative values but getting just the text.

engine1 <- tesseract(options = list(tessedit_create_hocr = "1"))
text <- ocr("http://jeroenooms.github.io/images/testocr.png", engine = engine1)
cat(text)

Thanks

**Comment by robszabo** [comment]
Hi,

With the latest release, it is possible to specify if you want hocr as output:

library(tesseract)
hocr <- ocr("text.tif", HOCR = T)
